const en = {
  documentTitle: "Card Reference | Amfibido",
  title: "Card Reference",
  subtitle: "Browse every card. Filter by level and type.",
  levelLabel: "Level",
  typeLabel: "Type",
  creatureLabel: "Creature",
  actionKindLabel: "Action",
  levels: {
    1: "1",
    2: "2",
    3: "3",
    4: "4",
    5: "5",
  },
  types: {
    fighter: "Fighter",
    action: "Action",
    equipment: "Equipment",
    sensei: "Sensei",
  },
  creatures: {
    frog: "Frog",
    toad: "Toad",
    turtle: "Turtle",
    lizard: "Lizard",
    crocodile: "Crocodile",
    salamander: "Salamander",
    snake: "Snake",
    spawn: "Spawn",
  },
  actionKinds: {
    combo: "Combo move",
    normal: "Normal",
  },
  empty: "No cards match these filters.",
  close: "Close",
  previous: "Previous card",
  next: "Next card",
  resultCount: "{count} cards",
};

const nl = {
  documentTitle: "Kaartreferentie | Amfibido",
  title: "Kaartreferentie",
  subtitle: "Bekijk alle kaarten. Filter op niveau en type.",
  levelLabel: "Niveau",
  typeLabel: "Type",
  creatureLabel: "Wezen",
  actionKindLabel: "Actie",
  levels: {
    1: "1",
    2: "2",
    3: "3",
    4: "4",
    5: "5",
  },
  types: {
    fighter: "Vechter",
    action: "Actie",
    equipment: "Uitrusting",
    sensei: "Sensei",
  },
  creatures: {
    frog: "Kikker",
    toad: "Pad",
    turtle: "Schildpad",
    lizard: "Hagedis",
    crocodile: "Krokodil",
    salamander: "Salamander",
    snake: "Slang",
    spawn: "Nakomeling",
  },
  actionKinds: {
    combo: "Combobeweging",
    normal: "Normaal",
  },
  empty: "Geen kaarten komen overeen met deze filters.",
  close: "Sluiten",
  previous: "Vorige kaart",
  next: "Volgende kaart",
  resultCount: "{count} kaarten",
};

export default {
  en,
  nl,
};
